# Use Node.js 22 image with Alpine Linux
FROM node:22-alpine AS builder

# Set working directory inside the container
WORKDIR /app

# Install git
RUN apk --no-cache add git

# Clone git repo
RUN git clone https://github.com/awalol/ds5dongle-config-web.git /app/

# Copy the package.json and the package-lock.json to the container
#COPY app/package*.json ./

# Install dependencies
RUN npm install

# Copy the source code into the container
#COPY app/ .

# Build the application
RUN npm run build


# Step 2 : Light production server
FROM nginx:alpine

# Copy the files generated by Vite to the Nginx folder
COPY --from=builder /app/dist /usr/share/nginx/html

#EXPOSE 80 # For developpement only
CMD ["nginx", "-g", "daemon off;"]